name: Lockfile refresh artifact

on:
  pull_request:

permissions:
  contents: read

jobs:
  generate:
    if: github.head_ref == 'test/testing-workflow-upgrade'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Regenerate lockfile
        run: pnpm install --no-frozen-lockfile

      - name: Upload generated lockfile
        uses: actions/upload-artifact@v4
        with:
          name: generated-pnpm-lock
          path: pnpm-lock.yaml
          retention-days: 1
